COGNITO_CLIENT_ID: !Ref UserpoolClient
COGNITO_CLIENT_SECRET: !GetAtt UserpoolClient.ClientSecret
MAIN_TABLE_NAME: !Ref MainTable
API_DOMAIN_NAME: api.yourdomain.com
ROUTE53_HOSTED_ZONE_ID: Z1234567890ABCDEFGHIJ
COGNITO_POOL_ID: !Ref Userpool
MEALS_BUCKET_NAME: !Ref MealsBucket
MEALS_CDN_DOMAIN_NAME: !If
  - ShouldSetupMealsCDNCustomDomain
  - ${env:MEALS_CDN_DOMAIN_NAME, ""}
  - !GetAtt MealsBucketCDN.DomainName
SQS_MEALS_QUEUE_URL: !GetAtt MealsQueue.QueueUrl
SQS_MEALS_DEAD_LETTER_QUEUE_URL: !GetAtt MealsDeadLetterQueue.QueueUrl
